Implemented the `DebianPackageInstaller` functionality.
Wolkabout/WolkGateway pull request #81
Opened 2022-03-03 12:01 UTC by nanavuletic

2022-03-03 12:01 UTC, nanavuletic commented
Depends on: https://github.com/Wolkabout/WolkConnect-Cpp/pull/61

2022-03-07 13:10 UTC, milanzlicic requested changes

2022-03-07 13:10 UTC, milanzlicic commented on CMakeLists.txt
> +        install(FILES out/manage-units.pkla DESTINATION /etc/polkit-1/localauthority/50-local.d)
Must be optional

2022-03-08 08:49 UTC, milanzlicic approved these changes

2022-03-08 08:55 UTC, merged